### ISSUE TITLE
Feature request: Delta display (ie. who is winning and by how much?)

### ISSUE THREAD

**Issue by movermeyer** [gregology/FaH_stats_page#1]
I'm always hovering over the ends of the graphs and computing the difference in my head.

Perhaps have a box that shows the current winner and the amount they are ahead by?

Mockup:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1459385/79515023-8c9d2980-8015-11ea-8928-70c169e95448.png">

**Comment by movermeyer** [comment]
Alternatively, or in addition: One could add the delta as its own line on the chart.

**Comment by gregology** [comment]
Added a chart showing the delta. It could do with some work to make it prettier :)
![image](https://user-images.githubusercontent.com/1595448/79696617-cbb4c000-824b-11ea-8217-a83e1bc2f6f0.png)

**Comment by movermeyer** [comment]
Looks good 🎉
